% Script to display the Chew Bahir data vs depth
%
% The script allows zooming and paning linked axes.
%
% 26 Aug 2019 - Trauth    

f(1) = figure('Position',[0 100 1200 800],...
    'Color',[1 1 1]);

a(1) = axes('Position',[0.05 0.05 0.04 0.8],...
    'Visible','Off',...
    'YDir','Reverse');
b(1) = axes('Position',[0.05 0.05 0.04 0.8],...
    'YDir','Reverse');
image(b(1),stratcolx,stratcoly,stratcol)
set(b(1),'XTick',[],...
    'XTickLabels',[])
ylabelstr = ['Splice Depth (m)'];
ylabel(b(1),ylabelstr)

a(2) = axes('Position',[0.1 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(2) = title(a(2),titlestr_a1,...
    'Rotation',45,...
    'Position',[min(get(a(2),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(2) = axes('Position',[0.1 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(2) = line(b(2),newdata_a1(:,2,1),newdata_a1(:,1,1));

a(3) = axes('Position',[0.21 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(3) = title(a(3),titlestr_a2,...
    'Rotation',45,...
    'Position',[min(get(a(3),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(3) = axes('Position',[0.21 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(3) = line(b(3),newdata_a2(:,2,1),newdata_a2(:,1,1));

a(4) = axes('Position',[0.32 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(4) = title(a(4),titlestr_a3,...
    'Rotation',45,...
    'Position',[min(get(a(4),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(4) = axes('Position',[0.32 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(4) = line(b(4),newdata_a3(:,2,1),newdata_a3(:,1,1));

a(5) = axes('Position',[0.43 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(5) = title(a(5),titlestr_a4,...
    'Rotation',45,...
    'Position',[min(get(a(5),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(5) = axes('Position',[0.43 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(5) = line(b(5),newdata_a4(:,2,1),newdata_a4(:,1,1));

a(6) = axes('Position',[0.54 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(6) = title(a(6),titlestr_a5,...
    'Rotation',45,...
    'Position',[min(get(a(6),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(6) = axes('Position',[0.54 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(6) = line(b(6),newdata_a5(:,2,1),newdata_a5(:,1,1));

a(7) = axes('Position',[0.65 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(7) = title(a(7),titlestr_a6,...
    'Rotation',45,...
    'Position',[min(get(a(7),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(7) = axes('Position',[0.65 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(7) = line(b(7),newdata_a6(:,2,1),newdata_a6(:,1,1));

a(8) = axes('Position',[0.76 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(8) = title(a(8),titlestr_a7,...
    'Rotation',45,...
    'Position',[min(get(a(8),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(8) = axes('Position',[0.76 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On');
l(8) = line(b(8),newdata_a7(:,2,1),newdata_a7(:,1,1));

a(9) = axes('Position',[0.87 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'XTickLabels',[],...
    'YTickLabels',[]);
t(9) = title(a(9),titlestr_a8,...
    'Rotation',45,...
    'Position',[min(get(a(9),'XLim')) -0.02],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontWeight','normal');
b(9) = axes('Position',[0.87 0.05 0.1 0.8],...
    'YDir','Reverse',...
    'YTickLabels',[],...
    'YGrid','On',...
    'Color','None');
l(9) = line(b(9),newdata_a8(:,2,1),newdata_a8(:,1,1));

linkaxes(b,'y')

z(1) = zoom(f(1));
set(z(1),'Motion','vertical');
p(1) = pan(f(1));
set(p(1),'Motion','vertical');








