% Script to display the wavelet power spectrum of Chew Bahir and other data
%
% 5 Sep 2019 - Trauth
% Extra 3D plot of wavelet power spectrum. We are using -abs(wt) with a
% different color axis.
f(11) = figure('Position',[0 800 800 500],...
    'Color',[1 1 1]);
a(11) = axes(...
    'ZLim',[-1 0],...
    'View',[-100 70]); hold on
s(11) = surf(newdata_a9(:,1),1./fr,-abs(wt),...
    'SpecularExponent',10,...
    'FaceLighting','phong',...
    'FaceColor','interp',...
    'EdgeColor','none');
colormap(jet)
caxis([-1 0.2])
li(11) = light('Parent',a(11),...
    'Style','local',...
    'Position',[145 70 155801]);
set(a(11),...
    'XLim',wavexlim,...
    'YLim',waveylim)
xlabel('Depth (m)')
ylabel('Wavelength (m)')
zlabel('Power')

%%
f(11) = figure('Position',[0 100 800 500],...
    'Color',[1 1 1]);
a(11) = axes('XLim',wavexlim,...
    'YLim',waveylim);
contourf(newdata_a9(:,1),1./fr,-abs(wt),15)
colormap(jet)
caxis([-1.5 0.4])
set(a(11),...
    'XGrid','On',...
    'YGrid','On',...
    'XLim',wavexlim,...
    'YLim',waveylim)
xlabel('Depth (m)')
ylabel('Wavelength (m)')
zlabel('Power')

%%




