% Script to display RQ/RQA results
%
% 1. Display RQ/RQA results
%
% 12 Sep 2019 - Trauth
% 17 Sep 2019 - Kraemer

RR(isnan(RR)==1) = 0;

% Create character array for legend.
RQA_Legend = {
     'RR'
     'DET'
     '<L>'
     'Lmax'
     'ENTR'
     'LAM'
     'TT'
     'Vmax'
     'RTmax'
     'T2'
     'RTE'
     'Clust'
     'Trans'};

% Figure window.
figure1 = figure('Units','normalized',...
    'Position',[.1 .1 .4 .9],...
    'Color',[1 1 1]);

% Time series.
axes1(1) = axes('Units','normalized',...
    'Position',[0.1 0.82 0.7 0.15],...
    'XLim',[min(t) max(t)],...
    'YLim',[ymin ymax],...
    'YDir','Reverse',...
    'LineWidth',1.5,...
    'Box','On',...
    'XGrid','On',...
    'XTickLabel',''); hold on
line(t,x,...
    'LineWidth',1,...
    'Color',[0 0 0])
tstr = strcat(datastr(varselectnum),"/",...
datastr(varselectdem));
title(tstr)

if filteroption == 1
    set(get(axes1(1),'Title'),...
    'String',horzcat('RQA based on detrended time series'),...
    'FontName','Helvetica',...
    'FontSize',12), hold on
end 

% Recurrence plot.
axes1(2) = axes('Units','normalized',...
    'Position',[0.1 0.16 0.7 0.7],...
    'XLim',[min(t) max(t)],...
    'YLim',[min(t) max(t)],...
    'LineWidth',1.5,...
    'Box','On',...
    'Layer','top',...
    'XGrid','On',...
    'XTickLabel','',...
    'YTickLabel',''); hold on
axis square xy
imagesc(t,t,RR)
colormap([1 1 1; 0 0 0])

% In case of threshold_calculation=='var', calculate the actual value 
% of threshold e.
if strcmp(threshold_calculation,'var')
    e = round(eps,2);
end

% Parameters.
str1 = ['m    = ',num2str(m)];
str2 = ['tau  = ',num2str(tau)];
if strcmp(threshold_calculation,'fix')
    str3 = ['e    = ',num2str(e),' (fixed)'];
elseif strcmp(threshold_calculation,'var')
    str3 = ['e    = ',num2str(e),' (fixed-var)'];
elseif strcmp(threshold_calculation,'fan')
    str3 = ['e    = ',num2str(e),' (adaptive)'];
end
str4 = ['w    = ',num2str(w)];
str5 = ['ws   = ',num2str(ws)];
str6 = ['norm = ',norm];
str7 = ['thei = ',num2str(theiler)];
str8 = ['lmin = ',num2str(l_min)];
str = {str1,str2,str3,str4,str5,str6,str7,str8};
text(min(t)+(max(t)-min(t))/20,...
     max(t)-(max(t)-min(t))/20,str,...
    'BackgroundColor',[1 1 1],...
    'EdgeColor',[1 1 1],...
    'VerticalAlignment','top')

% RQA.
axes1(3) = axes('Units','normalized',...
    'Position',[0.1 0.05 0.7 0.15],...
    'XLim',[min(t) max(t)],...
    'LineWidth',1.5,...
    'XGrid','On',...
    'Box','On'); hold on
line(axes1(3),t,r_win_e(RQA_Select(1),:),...
    'LineWidth',1,...
    'Color',[0 0.4453 0.7383])
legend(RQA_Legend{RQA_Select(1)},...
    'Box','Off')
xlabel('Age (kyr BP)')

linkaxes(axes1,'x')
set(axes1(2),'tag','rp2')

figstr = [
    'hh=findobj(figure1,''tag'',''rp2'');',...
    'xx = get(hh,''xlim'');'...
    'set(hh,''ylim'',xx)'];

set(figure1,'WindowButtonMotionFcn',figstr)

% Optional save graphics as PNG file.
if printres == 1
    agemodelchar = ...
         convertStringsToChars(agemodelstring(agemodeloption,:));
    printname = ['trauth_figure_',...
         num2str(-tmin),'_',...
         num2str(-tmax),'_',...
         num2str(filteroption),'_',...
         RQA_Legend{RQA_Select},'_',...
         agemodelchar,...
         '.png'];
    print(printname,'-dpng','-r300')
end


